# Generated by Django 6.1.1 on 2026-09-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='count',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
