# Generated by Django 6.1.1 on 2026-09-04 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_remove_medicine_manufacture_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='medicine',
            name='manufacture_date',
            field=models.DateField(default=datetime.date(2025, 1, 1)),
            preserve_default=False,
        ),
    ]
